"""Operate FC with OAS"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Core/05_oas_to_fc.ipynb.

# %% auto 0
__all__ = ['oas_to_fc']

# %% ../../nbs/Core/05_oas_to_fc.ipynb 2
from .oas_to_requests import *
from .fn_to_fc import *

# %% ../../nbs/Core/05_oas_to_fc.ipynb 3
import os
import json
import jsonref
import requests
from pprint import pp
import openai

# %% ../../nbs/Core/05_oas_to_fc.ipynb 6
def oas_to_fc(openapi_spec):
    functions = []

    for path, methods in openapi_spec["paths"].items():
        for method, spec_with_ref in methods.items():
            # 1. Resolve JSON references.
            spec = jsonref.replace_refs(spec_with_ref)

            # 2. Extract a name for the functions.
            function_name = spec.get("operationId")

            # 3. Extract a description and parameters.
            desc = spec.get("description") or spec.get("summary", "")

            schema = {"type": "object", "properties": {}}

            req_body = (
                spec.get("requestBody", {})
                .get("content", {})
                .get("application/json", {})
                .get("schema")
            )
            if req_body:
                schema["properties"]["requestBody"] = req_body

            params = spec.get("parameters", [])
            if params:
                param_properties = {
                    param["name"]: param["schema"]
                    for param in params
                    if "schema" in param
                }
                schema["properties"]["parameters"] = {
                    "type": "object",
                    "properties": param_properties,
                }

            functions.append(
                {"type": "function", "function": {"name": function_name, "description": desc, "parameters": schema}}
            )

    return functions
