"""Python module for detecting objects via YOLO"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Vision/03_yolo.ipynb.

# %% auto 0
__all__ = ['detect_objects']

# %% ../../nbs/Vision/03_yolo.ipynb 3
from typing import Optional
from ultralytics import YOLO
import json
import os

# %% ../../nbs/Vision/03_yolo.ipynb 11
def detect_objects(
    image_path: str, # Path/URL of image
    conf: Optional[float] = 0.25 # Confidence threshold
) -> str: # JSON format of detection results
    """Detect object in the input image using YOLO model."""
    # Load pretrained YOLO model
    model = YOLO('yolov8s.pt')
    
    # Get detections
    result = model(image_path, conf=conf, exist_ok=True)[0]

    # Save results as image
    save_dir = os.getenv("LLMCAM_DATA", "../data")
    output_path = image_path.split("/")[-1]
    result.save(filename=f"{save_dir}/detection_{output_path}")

    # Return summary of detection results as counts per class
    dict = {}
    for c in result.boxes.cls:
        dict[model.names[int(c)]] = dict.get(model.names[int(c)], 0) + 1
    
    # Return results as JSON-formatted string
    return json.dumps(dict)
