"""Python module to download and retrieve files with time & location specified"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_Utils/02_file_manager.ipynb.

# %% auto 0
__all__ = ['download_file', 'list_image_files', 'list_detection_files', 'list_demo3_files', 'list_plot_files']

# %% ../../nbs/02_Utils/02_file_manager.ipynb 3
import os
import glob
import requests

from typing import Optional

# %% ../../nbs/02_Utils/02_file_manager.ipynb 5
def download_file(
    url: str, # URL to download
    save_path: Optional[str] = None, # File name to save
):
    """Download a file from a give `url`"""
    with requests.get(url, stream=True) as response:
        response.raise_for_status()
        save_path = os.path.basename(url) if not save_path else save_path
        with open(save_path, "wb") as file:
            for chunk in response.iter_content(chunk_size=8192):
                if chunk:
                    file.write(chunk)
    return f"{save_path}"

# %% ../../nbs/02_Utils/02_file_manager.ipynb 12
def list_image_files()->str:
    """List all captured image files.
    file naming scheme is "cap_%Y.%m.%d_%H:%M:%S_<place name>.jpg"
    """
    return "\n".join(glob.glob(os.getenv("LLMCAM_DATA", "../data")+"/"+"cap_*.jpg"))

# %% ../../nbs/02_Utils/02_file_manager.ipynb 13
def list_detection_files() -> str:
  """List all detection images. File name starts with detection_"""
  return "\n".join(glob.glob(os.getenv("LLMCAM_DATA", "../data")+ "/" + "detection_*.jpg"))

# %% ../../nbs/02_Utils/02_file_manager.ipynb 14
def list_demo3_files() -> str:
  """List all parking lot frames. File name starts with demo3_"""
  return "\n".join(glob.glob(os.getenv("LLMCAM_DATA", "../data")+ "/" + "demo3_*.jpg"))

# %% ../../nbs/02_Utils/02_file_manager.ipynb 15
def list_plot_files() -> str:
  """List all plots. File name ends with plot"""
  return "\n".join(glob.glob(os.getenv("LLMCAM_DATA", "../data")+ "/" + "*plot.jpg"))
