# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llmcam',
                'doc_host': 'https://ninjalabo.github.io',
                'git_url': 'https://github.com/ninjalabo/llmcam',
                'lib_path': 'llmcam'},
  'syms': {'llmcam.core': {'llmcam.core.foo': ('core.html#foo', 'llmcam/core.py')}}}