# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llmcam',
                'doc_host': 'https://ninjalabo.github.io',
                'git_url': 'https://github.com/ninjalabo/llmcam',
                'lib_path': 'llmcam'},
  'syms': { 'llmcam.chat_ui': { 'llmcam.chat_ui.ActionButton': ('chat_ui.html#actionbutton', 'llmcam/chat_ui.py'),
                                'llmcam.chat_ui.ActionPanel': ('chat_ui.html#actionpanel', 'llmcam/chat_ui.py'),
                                'llmcam.chat_ui.ChatInput': ('chat_ui.html#chatinput', 'llmcam/chat_ui.py'),
                                'llmcam.chat_ui.ChatMessage': ('chat_ui.html#chatmessage', 'llmcam/chat_ui.py'),
                                'llmcam.chat_ui.index': ('chat_ui.html#index', 'llmcam/chat_ui.py'),
                                'llmcam.chat_ui.send': ('chat_ui.html#send', 'llmcam/chat_ui.py')},
            'llmcam.core': {'llmcam.core.foo': ('core.html#foo', 'llmcam/core.py')}}}
