"""Download a file in FC"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_downloader.ipynb.

# %% auto 0
__all__ = ['download_file']

# %% ../nbs/11_downloader.ipynb 3
import openai
import requests
import os

# %% ../nbs/11_downloader.ipynb 5
def download_file(
    url: str, # URL to download
    save_path:str=None, # file name to save
):
    "Download a file from a give `url`"
    with requests.get(url, stream=True) as response:
        response.raise_for_status()
        save_path = os.path.basename(url) if not save_path else save_path
        with open(save_path, "wb") as file:
            for chunk in response.iter_content(chunk_size=8192):
                if chunk:
                    file.write(chunk)
    return f"{save_path}"
