"""retrieve files with time & location specified"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/13_fle_manager.ipynb.

# %% auto 0
__all__ = ['list_image_files']

# %% ../nbs/13_fle_manager.ipynb 3
import os
import glob

# %% ../nbs/13_fle_manager.ipynb 7
def list_image_files()->str:
    """List all captured image files.
    file naming scheme is "cap_%Y.%m.%d_%H:%M:%S_<place name>.jpg"
    """
    return "\n".join(glob.glob(os.getenv("LLMCAM_DATA", "../data")+"/"+"cap_*.jpg"))
