# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_yolo_to_fc.ipynb.

# %% auto 0
__all__ = ['detect_objects']

# %% ../nbs/07_yolo_to_fc.ipynb 2
def detect_objects(
        image_path: str, # Path/URL of image
        conf: float=0.05 # Confidence threshold
    ) -> str: # JSON format of detection results
    """Run YOLO object detection on an input image."""
    model = torch.hub.load("ultralytics/yolov5", "yolov5s")
    model.conf = conf  # NMS confidence threshold
    
    results = model(image_path)
    count = results.pandas().xyxy[0]['name'].value_counts().to_dict()
    print(count)
    return json.dumps(count, indent=2)
